### ISSUE TITLE
package could not be loaded because of earlier compiled native modules

### ISSUE THREAD

**Issue by RitterLean** [viddo/atom-textual-velocity#18]
i get this error when I start a textual velocity. maybe Atom automatically updated itself so the package does not work anymore.

```
fsevents@0.3.8 – Module version mismatch. Expected 47, got 46.
fs-xattr@0.1.11 – Module version mismatch. Expected 47, got 46.
git-utils@4.1.2 – Module version mismatch. Expected 47, got 46.
microtime@2.0.0 – Module version mismatch. Expected 47, got 46.
```

**Comment by RitterLean** [comment]
Nevermind. Rebuilding it fixed the problem

**Comment by xHN35RQ** [comment]
Just had this problem in Atom 1.8.0. Package will not load until you rebuild the required packages. Not really a problem unless a user doesn't know to look for these sorts of issues. This is something I assume will be addressed as `textual-velocity` moves towards v1.
