### ISSUE TITLE
Proposal: Extracting #hashtags from files as tags for the note list

### ISSUE THREAD

**Issue by DivineDominion** [viddo/atom-textual-velocity#19]
I wondered where tags of this package would be coming from as this is not documented. Extracting hashtags would be trivial.

**Comment by viddo** [comment]
I've been considering that one myself. :)

> I wondered where tags of this package would be coming from as this is not documented. 

They're retrieved from a [file's "xattrs"](https://github.com/viddo/atom-textual-velocity/blob/master/lib/darwin.js) and using same namespace and format as [notational velocity](http://notational.net/) for this plugin to to be compatible with that app.

Documentation is essentially non-existing atm, I've planned to add that stuff later (v1) when I'm happy enough with the internals.

> Extracting hashtags would be trivial.

Yes, it should be trivial, but it isn't (right now); I'm refactoring all the internals as we speak to solve this, adding a new column (like the one you suggest here) should be as easy as registering a new column type and define its behavior. Something on the lines of:

```js
columns.register({
  title: 'Tags (from hashes)',
  prop_name: 'hash_tags',
  parse: function (file) {
    return file.content.match(/#\w+/g) || [];
  },
  present: function (file) {
    return file.hash_tags.map (tag) {
      return {
        type: 'tag',
        content: tag
      }
    };
  }
})
```

…so with the ^^^ and a file 'test.txt' and content `this is a test #example #tag` the new column would output:

| Name | Tags (from hashes) | Updated at | Created at | 
| --- | --- | --- | --- |
| test.txt | `example` `tag` | today | 1 day ago |

**Comment by viddo** [comment]
…I'll add this after I'm done with the refactoring. 
Thx for reporting btw!

**Comment by viddo** [comment]
Follow-up: This should be more or less straight-forward to implement, basically something like how [NV tags](https://github.com/viddo/atom-textual-velocity/blob/master/lib/service-consumers/nv-tags.js) was implemented.
