### ISSUE TITLE
fails to install on Windows 10

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#20]
Hi, 

for me, atom fails to install on Windows 10 (Visual Studio 2013, python 2.7 installed)
Could you please help me out?

C:\Users\User1\.atom\packages>apm install textual-velocity
Installing textual-velocity to C:\Users\User1\.atom\packages failed

> fs-xattr@0.1.11 install C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr
> node-gyp rebuild

C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr>if not defined npm_config_node_gyp (node "C:\Users\User1\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr\build\xattr.vcxproj]
  error.cc
  xattr.cc
..\src\xattr.cc(8): fatal error C1083: Datei (Include) kann nicht ge�ffnet werden: "sys/xattr.h": No such file or directory [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr\build\xattr.vcxproj]
..\src\error.cc(76): error C2065: 'ENOTBLK': nichtdeklarierter Bezeichner [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr\build\xattr.vcxproj]
..\src\error.cc(76): error C2051: case-Ausdruck ist keine Konstante [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\fs-xattr\build\xattr.vcxproj]

> microtime@2.0.0 install C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime
> node-gyp rebuild

C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime>if not defined npm_config_node_gyp (node "C:\Users\User1\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime\build\microtime.vcxproj]
  microtime.cc
     Bibliothek "C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime\build\Release\microtime.lib" und Objekt "C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime\build\Release\microtime.exp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  microtime.vcxproj -> C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\sifter\node_modules\microtime\build\Release\\microtime.node

> git-utils@4.1.2 install C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils
> node-gyp rebuild

C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\User1\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\libgit2.vcxproj]
  annotated_commit.c
  attr.c
  attr_file.c
  attrcache.c
  blame.c
  blame_git.c
  blob.c
  branch.c
  buf_text.c
  buffer.c
  cache.c
  checkout.c
  cherrypick.c
  clone.c
  commit.c
  commit_list.c
  config.c
  config_cache.c
  crlf.c
  config_file.c
  curl_stream.c
  date.c
  delta-apply.c
  delta.c
  describe.c
  diff.c
  diff_driver.c
  diff_file.c
  diff_patch.c
  diff_print.c
  diff_stats.c
  diff_tform.c
  diff_xdiff.c
  errors.c
  fetch.c
  fetchhead.c
  filebuf.c
  fileops.c
  filter.c
  fnmatch.c
  global.c
  graph.c
  hash.c
  hashsig.c
  ident.c
  ignore.c
  index.c
  indexer.c
  iterator.c
  merge.c
  merge_file.c
  message.c
  mwindow.c
  netops.c
  notes.c
  object.c
  object_api.c
  odb.c
  odb_loose.c
  odb_mempack.c
  odb_pack.c
  oid.c
  oidarray.c
  openssl_stream.c
  pack-objects.c
  pack.c
  path.c
  pathspec.c
  pool.c
  posix.c
  pqueue.c
  push.c
  rebase.c
  refdb.c
  refdb_fs.c
  reflog.c
  refs.c
  refspec.c
  remote.c
  repository.c
  reset.c
  revert.c
  revparse.c
  revwalk.c
  settings.c
  sha1_lookup.c
  signature.c
  socket_stream.c
  sortedcache.c
  stash.c
  status.c
  stransport_stream.c
  strmap.c
  submodule.c
  sysdir.c
  tag.c
  thread-utils.c
  tls_stream.c
  trace.c
  transaction.c
  transport.c
  tree-cache.c
  tree.c
  tsort.c
  util.c
  vector.c
  zstream.c
  auth.c
  auth_negotiate.c
  cred.c
  cred_helpers.c
  git.c
  http.c
  local.c
  smart.c
  smart_pkt.c
  smart_protocol.c
  ssh.c
  winhttp.c
  xdiffi.c
  xemit.c
  xhistogram.c
  xmerge.c
  xpatience.c
..\deps\libgit2\src\transports\winhttp.c(413): warning C4018: '<': Konflikt zwischen 'signed' und 'unsigned' [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\libgit2.vcxproj]
  xprepare.c
  xutils.c
  hash_generic.c
  dir.c
  error.c
  findfile.c
  map.c
  path_w32.c
  posix_w32.c
  precompiled.c
  pthread.c
  utf-conv.c
  w32_buffer.c
  w32_crtdbg_stacktrace.c
  w32_stack.c
  w32_util.c
  regex.c
  libgit2.vcxproj -> C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\\libgit2.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\zlib.vcxproj]
  adler32.c
  crc32.c
  deflate.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  zutil.c
  zlib.vcxproj -> C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\\zlib.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\http_parser.vcxproj]
  http_parser.c
  http_parser.vcxproj -> C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\\http_parser.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\git.vcxproj]
  repository.cc
     Bibliothek "C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\git.lib" und Objekt "C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\git.exp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  git.vcxproj -> C:\Users\User1\AppData\Local\Temp\apm-install-dir-116510-12812-4jpq90\node_modules\textual-velocity\node_modules\scandal\node_modules\git-utils\build\Release\\git.node

npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\User1\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User1\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User1\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User1\\.atom\\.apmrc" "install" "C:\\Users\\User1\\AppData\\Local\\Temp\\d-116510-12812-11krvu7\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! fs-xattr@0.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-xattr@0.1.11 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.

C:\Users\User1\.atom\packages>apm install fxattr
Installing fxattr to C:\Users\User1\.atom\packages failed
Request for package information failed: Not Found
C:\Users\User1\.atom\packages>apm install fx-attr
Installing fx-attr to C:\Users\User1\.atom\packages failed
Request for package information failed: Not Found
C:\Users\User1\.atom\packages>

**Comment by viddo** [comment]
Sorry for this several months late reply… for some reason I didn't get the notification of this issue. 😞 

I'm not a Windows user myself, but looking at the stack trace it seems like the [fs-xattrs](https://github.com/viddo/atom-textual-velocity/blob/0ab50dd6c898c200c4d6ed096fc01237da97ab30/package.json#L29) dependency (used to read/write embedded tags from a file) does not work for Windows.
I'm currently rewriting stuff and should be done soon (see the [`clean`](https://github.com/viddo/atom-textual-velocity/tree/clean) branch), I'll make sure to fix this as part of that.

Thanks for the report! 🙇

**Comment by capcionista** [comment]
Thank you for your answer. I'm really looking forward to the update.
I tried installing the new package from the clean branch, which gave an error: "Cannot find module bacon js".
How can I fix this?

**Comment by viddo** [comment]
How did you _installing the new package from the clean branch_ exactly? Where do you get/see that error?

**Comment by capcionista** [comment]
I downloaded and unzipped the package and then ran npm install in the package folder.

When in atom I run "Start textual velocity" - it shows:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: J
**Thrown From**: [textual-velocity](https://github.com/viddo/atom-textual-velocity) package, v0.7.0


### Stack Trace

Failed to activate the textual-velocity package

```
At Cannot find module 'baconjs'

Error: Cannot find module 'baconjs'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Franz\.atom\packages\atom-textual-velocity-clean\lib\path-watcher-factory.js:11:16)
    at Module._compile (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Franz\.atom\packages\atom-textual-velocity-clean\lib\session.js:11:27)
    at Module._compile (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Franz/.atom/packages/atom-textual-velocity-clean/lib/main.js:3:51)
    at Module._compile (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:718:27)
    at Package.module.exports.Package.activateNow (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Franz\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
```

### Commands

```
     -0:15.9.0 bracket-matcher:select-inside-brackets (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.1.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:10.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.2.0 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -0:09.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 textual-velocity:start-session (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.gfm": [
        "txt"
      ]
    },
    "disabledPackages": [
      "symbols-view"
    ],
    "softWrap": true,
    "themes": [
      "one-dark-ui",
      "i-a--writer-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
textual-velocity, v0.7.0 (inactive)
file-icons, v1.7.19 (active)
FlipPage, v1.0.5 (active)
global-shortcuts, v0.2.0 (inactive)
i-a--writer-dark-syntax, v0.0.0 (active)
language-gfm, v0.86.0 (active)
markdown-writer, v2.3.4 (inactive)
minimap-find-and-replace, v4.5.1 (active)
navigate, v0.1.15 (active)
planner, v0.3.2 (active)
typewriter, v0.3.5 (active)
wordcount, v2.6.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by viddo** [comment]
Try `apm rebuild`, or even deleting node_modules and run `apm install` instead of `npm install`, some packages need to be rebuilt for Atom to work. Baconjs is not one of them though, but there might have been some error during the npm install that caused baconjs to not be installed. 

Also check if it outputs any errors in the terminal when running those commands.

**Comment by capcionista** [comment]
Wow it works. Thank you, this is amazing!
Are there any concerns for fatal errors that might affect the note collection using the current clean branch? Will the index be updated if notes are edited outisde atom?
Otherwise I will directly switch to using the package for my collection.

**Comment by viddo** [comment]
Yay, great to hear! 👍 
FYI, I plan to release a new version (0.8) sometime after the weekend, as long as I don't encounter any bugs before then.

> Are there any concerns for fatal errors that might affect the note collection using the current clean branch? 

No, there's no "fatal errors" that would corrupt your files or such, if that's what you mean? 

> Will the index be updated if notes are edited outside atom?

Yes.

**Comment by capcionista** [comment]
Great. Thank you very, very much!

**Comment by capcionista** [comment]
Can you tell me how I can register a global shortcut that focusses on search when the Atom window is closed but the Textual Velocity Session has started? I have registered a global shortcut for "Focus on Search", but it doesn't work outside atom.

**Comment by viddo** [comment]
The init script located at https://github.com/viddo/atom-textual-velocity/blob/clean/docs/recommended-usage/.atom/init.coffee should do the trick, it's what I'm using. You need to restart Atom after changing it for it to take effect

**Comment by capcionista** [comment]
Great! It works (though sometimes it says the command could not be registered, I guess this depnds on other programmes being opened.
How can I change the note directory as long as there is no option in the settings?

**Comment by capcionista** [comment]
I was able to change the path in /lib/default-config.js and to adjust the default filetype in presenter.js, but I couldn't find a way to allow capital letters in filenames.

**Comment by viddo** [comment]
> Great! It works (though sometimes it says the command could not be registered, I guess this depnds on other programmes being opened.

Yes, if the combo is already taken by another application (or another instance of Atom) it can't be registered. There's no way (to my knowledge) how to check what application have registered what keycombos.

> I was able to change the path in /lib/default-config.js and to adjust the default filetype in presenter.js

You should not need to modify the code to change it, there's a config setting under _Preferences > Packages > textual-velocity_ where you can change it: 
<img width="706" alt="screen shot 2016-10-03 at 08 10 02" src="https://cloud.githubusercontent.com/assets/978461/19042417/d6572906-8940-11e6-9fab-1610f222963c.png">

> How can I change the note directory and switch default filetype from md to txt as long as there is no option in the settings?

Not supported at the moment, created a separate issue for it #22
