### ISSUE TITLE
No Capital Letters allowed in search field

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#21]
I cannot type capital letters in the search field. For search of course, this is of minor importance, but when it comes to creating files from the keywords + Enter, capital letters can be helpful.

OS: Windows 10

**Comment by viddo** [comment]
That's a weird behavior indeed… will investigate. Thanks for reporting it!

**Comment by viddo** [comment]
Fixed in 16cd08f
Since this report was for a unreleased dev branch I'll close it ahead of time.
