### ISSUE TITLE
Make title-match priority

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#26]
First of all, thank you so much for your work! Textual Velocity is amazing and it's exactly what I've been looking for since several months. Thank you!

To optimize the search, I would suggest to make tile-matches a priority, i.e. when the search terms are part of the filetitle, make this file come first even if there are more matches in the note body of other notes.

**Comment by viddo** [comment]
Glad that scratching my own itch is also helping someone else. 🙇 

That's a good and reasonable enhancement! Need to look into how I'd solve it though, since it will require some way of defining multiple sort fields (and priorities) per column. I'll look into it.
