### ISSUE TITLE
slow navigate package

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#31]
The navigate package that I use for inter-file links (filename in brackets) + bracket-match + navigate forward opens filename.txt does not work for me in atom-textual-velocity, unless a project folder is opened in the sidebar. This however considerably slows down the search and everything.
Can you see why that happens?

**Comment by xHN35RQ** [comment]
Yes, this is based on how the navigate package determines the path of the current file. I think it depends on the existence of a project folder, which if not present, means that there is no valid path available for the current file.

You can try other packages which offer similar functionality: http://faq.surge.sh/nvalt-notational-velocity-atom/#note-linking

**Comment by viddo** [comment]
@capcionista Not sure, I would have to debug that package to see what it is doing that makes things slow down so much. What is the name of the package you use? 

That said, I'm going to address the navigating (preview) in #25 soon enough, so I think this would be solved by that anyway. 

@xHN35RQ thx for the link, wasn't aware of it, there are some interesting thoughts on that page. 👍

**Comment by xHN35RQ** [comment]
@capcionista is using the navigate package: https://atom.io/packages/navigate

For reference, here is how the [open-sesame](https://github.com/stevenhauser/open-sesame) package returns a path for each current file even in the absence of a project folder:

https://github.com/stevenhauser/open-sesame/blob/master/lib/open-sesame.coffee#L15-#L42

And here is how I do it in my [atom-plumber](https://github.com/xHN35RQ/atom-plumber) package, based on code I borrowed from the [shell-it](https://github.com/mark-hahn/shell-it/) package:

https://github.com/xHN35RQ/atom-plumber/blob/master/lib/atom-plumber.js#L74-#L87

**Comment by xHN35RQ** [comment]
As you can see here, the navigate package doesn't have a very robust path acquisition method, so it fails when there is no project-folder.

https://github.com/skandasoft/navigate/blob/master/lib/navigate.coffee#L121-#L128

**Comment by viddo** [comment]
Just released a new version (0.10.0) which resolves #25, so selection preview should be instant and don't suffer this issue.

Once a file is opened (enter or focus on the preview), the default text editor is used so from there on there's not much I can from my end regarding 3rd party packages, you'd better report issues to the specific package that's causing the slowness.
