### ISSUE TITLE
Improve preview behavior on selection and open action

### ISSUE THREAD

**Issue by viddo** [viddo/atom-textual-velocity#43]
Right now when selecting a note it always opens a preview editor which stays in the background. More often than not I find the preview is "getting in the way". E.g. closing an open note text editor it re-selects the previous note upon the preview is opened next, even though I'm done with it. Therefore, I'm considering the following changes:

1. Upon an open-selected-note (<kbd>enter</kbd>/double-click the note) or focus-preview action:
    - **Current behavior:** A text editor is opened & focused (preview editor left open in the background).
    - **Proposed change:** Always close the preview (in addition to open&focus the normal text editor).

2. When a note is selected:
    - **Current behavior:** A preview is always opened/updated.
    - **Proposed behavior:** If there exists a normal text editor that corresponds to the note open that editor instead and close the preview (if there is any) - If not, open/update the preview.

Thoughts? Or any other proposals?

**Comment by xHN35RQ** [comment]
I noticed this too. I think your proposed behaviour in 2. mirrors the way Atom handles file opening by default so it make sense to me!
