### ISSUE TITLE
Focus on search on closing a text editor

### ISSUE THREAD

**Issue by viddo** [viddo/atom-textual-velocity#47]
As proposed in https://github.com/gotjoshua/atom-textual-velocity/issues/3#issuecomment-267409693

> I like the behavior that if i search, find and open a note.... then close it again, my focus goes back up to the search (like cmd-L)

I think it's a good idea. That said, perhaps there are others that prefer the current behavior?

Also, meanwhile it's trivial to add in one's init config:

```js
atom.workspace.onDidDestroyPaneItem(function() {
  atom.commands.dispatch(atom.views.getView(atom.workspace), 'textual-velocity:focus-on-search')
})
```

Vote by thumbs-up/down reaction to this issue, and/or give your opinion if you have something to add.

**Comment by gotjoshua** [comment]
Glad you like the proposal @viddo ! 
That init function seems to trigger on every DestroyPaneItem event.
Even if i select an item and hit return to open it, i end up back in the search bar.
In that case (after hitting return) I'd prefer to give focus to the newly opened editor.
If I have two items open and close one, i'd only trigger the focus-on-search command when all panes are closed.
Therefore I'd use the following coffeescript in my init:
```coffeescript
# focus-on-search when there are no panes left
atom.workspace.onDidDestroyPaneItem ->
  if atom.workspace.getPaneItems().length == 0
    atom.commands.dispatch(atom.views.getView(atom.workspace), 'textual-velocity:focus-on-search')
```

**Comment by viddo** [comment]
Added this to the package itself finally, so no need for custom init for this one anymore.

In my implementation I'm checking `atom.workspace.getTextEditors()` instead, latest version of Atom might contain panes items that never closes (treeview, diagnostics, …).
