### ISSUE TITLE
No longer loads pre-existing files or creates new ones

### ISSUE THREAD

**Issue by ian-13** [viddo/atom-textual-velocity#71]
### Description

Upgraded to the latest release (v0.14.1), on 1.17.0 for atom. On Windows.

### Steps to Reproduce
1. Launch textual velocity with hotkey (ctrl + shift + p and select from Start Session from menu)

**Expected behavior:**
Previously loaded files in location specified in Textual Velocity settings, or default location.
Also could save files to this location.

**Actual behavior:**

Doesn't load any pre-existing files (.md and .txt).
Also, when trying to save a new file by entering name in search at top and saving, get the following error:
"TestFile.md could not be saved. Error: undefined"

**Comment by viddo** [comment]
Only use Mac myself so might be a bit hard to debug… that said, without more info and just interpreting the the symptoms you're experiencing I'd guess that the plugin can't read the directory, for whatever reason.

- I'm using v1.17.0, which appears to be [latest official version](https://github.com/atom/atom/releases). Can you confirm that you're really using v1.17.1? If so, how did you get that version? If unsure, try to reinstall [Atom from official source](https://atom.io/) to rule this one out at least.

- Can you double check the settings of the textual-velocity package. Does it still have the notes `path` you'd expect? Do you use the default? Check that the path exists/permissions are still OK.

- When/if you get that error, can you open the develop tools and see if you get more details there?:
![screen shot 2017-05-22 at 20 00 10](https://cloud.githubusercontent.com/assets/978461/26336793/522ef39e-3f29-11e7-8b33-2961ac1019b0.png)

If nothing else works, you could install the previous version until we've figured out a solution. On *nix that can be done by `apm install textual-velocity@0.14.0`. See the [official Atom discussion board on (_apm install window_)](https://discuss.atom.io/search?q=apm%20install%20windows) if `apm` doesn't work as expected.

**Comment by ian-13** [comment]
Sorry, that was a typo, I am on 1.17.0. Corrected above.

The path and permissions seem to be fine, and there weren't any errors in the dev tools console.

I ended up reverting back to 0.14.0 as suggested and that works as expected.

**Comment by ian-13** [comment]
Actually, the notes load and save fine in 0.14.1 with an _absolute_ path. I was using a funky relative path that hadn't changed, so I'm surprised it broke -- but I'd prefer to use the absolute path anyway. Thanks for the debug suggestions, they were very helpful!

**Comment by viddo** [comment]
Glad to hear it works again. 🙌 

Although, it sounds like _relative_ paths might be a problem on Windows. Could be that I've missed some edge-case I guess. What was the the "funky relative path" you used before? Would like to fix it if I can.

Btw, thanks for the report!

**Comment by ian-13** [comment]
It was ~/../../Dropbox/Notes
Had been using it for a while, though it's a pretty ugly path :)

**Comment by viddo** [comment]
Thanks!
Still find it weird that stopped working now. Could be due to one of the dependencies that I also updated while at it in the last release. Either way, I have created an issue to improve the path checks 👉  #72
