### ISSUE TITLE
key bindings on linux

### ISSUE THREAD

**Issue by stefanix** [viddo/atom-textual-velocity#73]
The key bindings don't work under linux when the editor is focused. I had to add something like the following to the keymap file:

'atom-text-editor':
  'ctrl-shift-C': 'textual-velocity:toggle-panel'
  'ctrl-`': 'textual-velocity:focus-on-search'

**Comment by stefanix** [comment]
Currently using this:

'atom-text-editor':
  'ctrl-alt-`': 'textual-velocity:toggle-panel'
  'ctrl-`': 'textual-velocity:focus-on-search'

'atom-workspace':
  'ctrl-alt-`': 'textual-velocity:toggle-panel'
  'ctrl-`': 'textual-velocity:focus-on-search'

**Comment by viddo** [comment]
Thanks for reporting!

Hmm, I don't use linux myself, but from your description sounds like the selector in the keymap is off somehow. Sounds like you found a work round for now at least.

I'll try to investigate this at some point.
