### ISSUE TITLE
error in init.coffee file in recommended usage

### ISSUE THREAD

**Issue by gotjoshua** [viddo/atom-textual-velocity#76]
[Line 27 from the init.coffee file in recommended usage](https://github.com/viddo/atom-textual-velocity/blob/master/docs/recommended-usage/.atom/init.coffee#L27) is throwing an error.
```
TypeError: atom.packages.getActivePackage(...).mainModule.createView is not a function
```

**Comment by viddo** [comment]
Thx for the report!
