### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by viddo** [viddo/atom-textual-velocity#8]
My personal notes are like 5Mb in total, it takes like 5 sec to load. Not horrible but could very likely be speeded up by some simple changes and profiling. 

E.g. delay stat calls on each file to after all files are loaded.

**Comment by DivineDominion** [comment]
My 3700 notes take quite a while to load for the first time, too :)

Couldn't the plugin write an index to `~/.atom` and update it when starting? Then it wouldn't have to do all the work for every session.

**Comment by viddo** [comment]
Yes, that, and doing a diff between changed files since last session and only update the index of those files async. By coincidence I'm actually working on it, I hope to have it done soon enough. :)

**Comment by viddo** [comment]
> Couldn't the plugin write an index to ~/.atom and update it when starting? Then it wouldn't have to do all the work for every session.

This was implemented as part of v0.8 that was just released, the first, initial scan (until all notes have been processed) still takes some time but after that the initial load should be much faster.
