### ISSUE TITLE
Upgrade or change chokidar dependency?

### ISSUE THREAD

**Issue by viddo** [viddo/atom-textual-velocity#9]
At the time of writing, is [using version 1.0.6](https://github.com/viddo/atom-textual-velocity/blob/master/package.json#L25) of [chokidar](https://github.com/paulmillr/chokidar), because any newer version fails to install/build (`apm rebuild`), need to investigate what the real issue is.

edit:
Related issues:
- https://github.com/mapbox/node-pre-gyp/issues/188
- https://github.com/strongloop/fsevents/issues/93

Other [packages](https://github.com/agrc/atom-amdbutler/commit/288f01ca604cd37e985bca9fe782157ebba0256d) went with using https://github.com/shama/gaze instead.

**Comment by hedefalk** [comment]
I went down to chokidar 1.0.6 too in the end. Gaze didn't work for my super-basic use case of just watching a file :)

https://github.com/hedefalk/node-file-watchers-test

**Comment by viddo** [comment]
Thx for replying! That's the version I'm currently relying on too… :smile:

**Comment by viddo** [comment]
For future reference, this was pending a fix that was released as part of [Atom v1.10.x](https://github.com/atom/atom/pull/12240/), more specifically v0.12.3 of atom/apm which includes [_Fix missing and hardcoded flags_](https://github.com/atom/apm/pull/596).
